### PR TITLE
Changed "Lenght" to "Length"

### PR DESCRIPTION
**Pull request by Tamilist**

### CODE REVIEW

**Comment by MartinChavez** [comment]
Thanks @Tamilist ! good catch.

**Comment by Tamilist** [comment]
No problem :) This was my first contribution on github so I thought I'd start small.

**Comment by MartinChavez** [comment]
What an honor then! Thanks for taking some time to look at the project, feel free to add new concepts/tests.

**Comment by sdogruyol** [comment]
OSS is ❤️

**Comment by FagnerMartinsBrack** [comment]
[Given enough eyeballs... all bugs are shallow](https://en.wikipedia.org/wiki/Linus%27s_Law)

**Pull request merged**
